FROM node:24

WORKDIR /app
COPY . .
COPY ./.env.dev .env

RUN corepack enable
RUN pnpm i

RUN apt update
RUN apt install -y mc nano iputils-ping net-tools telnet

#CMD ["ping", "-i", "6000", "google.com"]
CMD ["pnpm", "start"]
