import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Data files sitting next to this migration; `nest-cli.json` copies
 * `migrations/**\/*.tsv` into `dist/migrations`, so `__dirname` resolves them
 * both under ts-node (dev) and in the compiled production image. All four are
 * generated by `pnpm kb-verify-merge` from the checked-in verification-round
 * outputs (`docs/kb-research/verify/out/`), re-gated through the same
 * `KbGateUtils` policy that graded the seed.
 */
const PRODUCER_TSV = '1788030413011-kb-verification-import.producer.tsv';

const ALIAS_TSV = '1788030413011-kb-verification-import.alias.tsv';

const FLAVOR_TSV = '1788030413011-kb-verification-import.flavor.tsv';

const RULE_TSV = '1788030413011-kb-verification-import.rule.tsv';

/**
 * Statuses this import may stamp. Anything else in the file is a generator
 * bug and fails the migration.
 */
const STATUSES = ['auto', 'unverified', 'rejected'];

/**
 * Applies the verification round to the knowledge base.
 *
 * The seed round economized on the long tail (its brief said so outright), so
 * 437 producers sat withheld with honest `low` confidence. A fleet of
 * web-grounded verification agents re-evidenced every row; this migration
 * writes the outcome: facts corrected, sources attached, and the shared
 * auto-gate's verdict stamped — `auto` rows go live, still-unproven rows stay
 * `unverified`, and rows that are not whisky producers at all become
 * `rejected`.
 *
 * Two guarantees the import makes:
 *
 * - **A person's decision always wins.** Updates apply only where the row is
 *   still `unverified` — a producer the owner promoted, rejected or verified
 *   between the dump and this deploy is left exactly as they set it.
 * - **Fail-closed, like every knowledge-base importer.** An unknown country,
 *   type, flavor, status or a malformed line aborts the whole migration
 *   rather than importing a row whose columns no longer mean what they say.
 *
 * Storing the verdicts changes nothing a filter reads until the catalogue is
 * re-resolved; the boot-time apply pass (`KbBootApplyService`) runs right
 * after deploy, so no manual step follows this migration.
 */
export class KbVerificationImport1788030413011 implements MigrationInterface {
  public name = 'KbVerificationImport1788030413011';

  public async up(queryRunner: QueryRunner): Promise<void> {
    const producers = this.read(PRODUCER_TSV, 15);

    if (!producers.length) {
      throw new Error(`${PRODUCER_TSV} holds no producers`);
    }

    const badStatus = producers
      .find((row) => !STATUSES.includes(row[11] ?? ''));

    if (badStatus) {
      throw new Error(
        `${PRODUCER_TSV}: '${badStatus[0] ?? ''}' has status `
          + `'${badStatus[11] ?? ''}'`,
      );
    }

    await this.assertCountries(queryRunner, producers);
    await this.assertTypes(queryRunner, producers);

    await this.updateProducers(queryRunner, producers);
    await this.insertProducers(queryRunner, producers);
    await this.linkReferences(queryRunner, producers);

    const aliases = this.read(ALIAS_TSV, 3);

    if (aliases.length) {
      await this.insertAliases(queryRunner, aliases);
    }

    const flavors = this.read(FLAVOR_TSV, 6);

    if (flavors.length) {
      await this.assertFlavors(queryRunner, flavors.map((row) => row[1]));
      await this.insertFlavors(queryRunner, flavors);
    }

    const rules = this.read(RULE_TSV, 9);

    if (rules.length) {
      await this.assertFlavors(
        queryRunner,
        rules.map((row) => row[3]).filter(Boolean),
      );

      await this.insertRules(queryRunner, rules);
    }
  }

  /**
   * Partial by design. The producer updates are irreversible — the previous
   * values were not recorded, and re-running the seed importers would not
   * restore the review decisions made since. What can be removed precisely
   * is removed: the aliases, house styles and rules this file added. Producer
   * rows (updated or inserted) are left in place; re-running
   * `pnpm reconcile-flavors` after a manual status change is the documented
   * way to unwind a promotion.
   *
   * @param queryRunner - The running migration's query runner.
   */
  public async down(queryRunner: QueryRunner): Promise<void> {
    const aliases = this.read(ALIAS_TSV, 3);

    if (aliases.length) {
      await queryRunner.query(
        'DELETE FROM producer_alias WHERE key = ANY($1::text[])',
        [aliases.map((row) => row[0])],
      );
    }

    const flavors = this.read(FLAVOR_TSV, 6);

    if (flavors.length) {
      await queryRunner.query(
        `DELETE FROM producer_flavor pf
         USING unnest($1::text[], $2::text[]) AS v(slug, flavor),
               producer p, flavor f
         WHERE p.slug = v.slug AND f.name = v.flavor
           AND pf."producerId" = p.id AND pf."flavorId" = f.id`,
        [
          flavors.map((row) => row[0]),
          flavors.map((row) => row[1]),
        ],
      );
    }

    const rules = this.read(RULE_TSV, 9);

    if (rules.length) {
      await queryRunner.query(
        `DELETE FROM flavor_rule fr
         USING unnest($1::text[], $2::text[]) AS v(slug, pattern), producer p
         WHERE p.slug = v.slug
           AND fr."producerId" = p.id AND fr.pattern = v.pattern`,
        [
          rules.map((row) => row[0]),
          rules.map((row) => row[1]),
        ],
      );
    }
  }

  /**
   * Parses one data file. A line without the exact field count means a value
   * contained a tab and every field after it has shifted, so the migration
   * fails rather than importing columns that no longer mean what they say.
   *
   * @param file - File name beside this migration.
   * @param fields - Required fields per line.
   * @returns One field array per line; empty when the file is empty.
   * @throws {Error} When a line is malformed.
   */
  private read(file: string, fields: number): string[][] {
    const text = readFileSync(join(__dirname, file), 'utf8');
    const rows: string[][] = [];

    text.split('\n').forEach((line, index) => {
      if (!line.trim()) {
        return;
      }

      const parts = line.split('\t');

      if (parts.length !== fields) {
        throw new Error(
          `${file}:${index + 1} has ${parts.length} fields, `
            + `expected ${fields}`,
        );
      }

      rows.push(parts);
    });

    return rows;
  }

  /**
   * Fails the migration when a producer names a country the database has no
   * row for.
   *
   * @param queryRunner - The running migration's query runner.
   * @param rows - The parsed producers.
   * @throws {Error} Naming the unknown codes.
   */
  private async assertCountries(
    queryRunner: QueryRunner,
    rows: string[][],
  ): Promise<void> {
    const codes = [...new Set(rows.map((row) => row[3]).filter(Boolean))];

    if (!codes.length) {
      return;
    }

    const found = await queryRunner.query(
      'SELECT code FROM country WHERE code = ANY($1::text[])',
      [codes],
    ) as { code: string }[];

    const known = new Set(found.map((row) => row.code));
    const missing = codes.filter((code) => !known.has(code));

    if (missing.length) {
      throw new Error(
        `${PRODUCER_TSV}: unknown country codes ${missing.join(',')}`,
      );
    }
  }

  /**
   * Fails the migration when a producer names a whisky type the database has
   * no row for — the column stores the name, so an unknown value would sit
   * there looking valid and never match anything.
   *
   * @param queryRunner - The running migration's query runner.
   * @param rows - The parsed producers.
   * @throws {Error} Naming the unknown types.
   */
  private async assertTypes(
    queryRunner: QueryRunner,
    rows: string[][],
  ): Promise<void> {
    const names = [...new Set(rows.map((row) => row[7]).filter(Boolean))];

    if (!names.length) {
      return;
    }

    const found = await queryRunner.query(
      'SELECT name FROM type WHERE name = ANY($1::text[])',
      [names],
    ) as { name: string }[];

    const known = new Set(found.map((row) => row.name));
    const missing = names.filter((name) => !known.has(name));

    if (missing.length) {
      throw new Error(
        `${PRODUCER_TSV}: unknown whisky types ${missing.join(',')}`,
      );
    }
  }

  /**
   * Fails the migration when a house style or rule names a flavor outside
   * the vocabulary.
   *
   * @param queryRunner - The running migration's query runner.
   * @param names - Flavor names referenced by the file.
   * @throws {Error} Naming the unknown flavors.
   */
  private async assertFlavors(
    queryRunner: QueryRunner,
    names: (string | undefined)[],
  ): Promise<void> {
    const wanted = [...new Set(names.filter(Boolean))] as string[];

    if (!wanted.length) {
      return;
    }

    const found = await queryRunner.query(
      'SELECT name FROM flavor WHERE name = ANY($1::text[])',
      [wanted],
    ) as { name: string }[];

    const known = new Set(found.map((row) => row.name));
    const missing = wanted.filter((name) => !known.has(name));

    if (missing.length) {
      throw new Error(`unknown flavors ${missing.join(',')}`);
    }
  }

  /**
   * Rewrites the stored rows the verification round re-evidenced — but only
   * where the row still holds the seed's verdict. `status = 'unverified'` in
   * the WHERE clause is the guarantee that a decision a person made between
   * the dump and this deploy (promote, reject, verify) is never overwritten
   * by a batch job.
   *
   * @param queryRunner - The running migration's query runner.
   * @param rows - The parsed producers.
   */
  private async updateProducers(
    queryRunner: QueryRunner,
    rows: string[][],
  ): Promise<void> {
    await queryRunner.query(
      `UPDATE producer p SET
         name = v.name,
         kind = v.kind,
         "countryId" = c.id,
         region = nullif(v.region, ''),
         "legalRegion" = nullif(v."legalRegion", ''),
         owner = nullif(v.owner, ''),
         "defaultTypeName" = nullif(v."defaultTypeName", ''),
         "peatProfile" = v."peatProfile",
         status = v.status,
         confidence = nullif(v.confidence, ''),
         "sourceUrls" = nullif(v."sourceUrls", ''),
         note = nullif(v.note, ''),
         "updatedAt" = now()
       FROM unnest(
         $1::text[], $2::text[], $3::text[], $4::text[], $5::text[],
         $6::text[], $7::text[], $8::text[], $9::text[], $10::text[],
         $11::text[], $12::text[], $13::text[]
       ) AS v(slug, name, kind, "countryCode", region, "legalRegion", owner,
              "defaultTypeName", "peatProfile", status, confidence,
              "sourceUrls", note)
       LEFT JOIN country c ON c.code = nullif(v."countryCode", '')
       WHERE p.slug = v.slug AND p.status = 'unverified'`,
      [
        rows.map((row) => row[0]),
        rows.map((row) => row[1]),
        rows.map((row) => row[2]),
        rows.map((row) => row[3]),
        rows.map((row) => row[4]),
        rows.map((row) => row[5]),
        rows.map((row) => row[6]),
        rows.map((row) => row[7]),
        rows.map((row) => row[8]),
        rows.map((row) => row[11]),
        rows.map((row) => row[12]),
        rows.map((row) => row[13]),
        rows.map((row) => row[14]),
      ],
    );
  }

  /**
   * Inserts the rows the knowledge base lacked — the parents and bottlers the
   * verification round discovered while pinning down its assigned rows.
   * `ON CONFLICT DO NOTHING` keeps the import idempotent and leaves any row
   * that appeared meanwhile untouched.
   *
   * @param queryRunner - The running migration's query runner.
   * @param rows - The parsed producers.
   */
  private async insertProducers(
    queryRunner: QueryRunner,
    rows: string[][],
  ): Promise<void> {
    await queryRunner.query(
      `INSERT INTO producer
         (slug, name, kind, "countryId", region, "legalRegion", owner,
          "defaultTypeName", "peatProfile", status, confidence, "sourceUrls",
          note)
       SELECT v.slug, v.name, v.kind, c.id,
              nullif(v.region, ''), nullif(v."legalRegion", ''),
              nullif(v.owner, ''), nullif(v."defaultTypeName", ''),
              v."peatProfile", v.status,
              nullif(v.confidence, ''), nullif(v."sourceUrls", ''),
              nullif(v.note, '')
       FROM unnest(
         $1::text[], $2::text[], $3::text[], $4::text[], $5::text[],
         $6::text[], $7::text[], $8::text[], $9::text[], $10::text[],
         $11::text[], $12::text[], $13::text[]
       ) AS v(slug, name, kind, "countryCode", region, "legalRegion", owner,
              "defaultTypeName", "peatProfile", status, confidence,
              "sourceUrls", note)
       LEFT JOIN country c ON c.code = nullif(v."countryCode", '')
       ON CONFLICT (slug) DO NOTHING`,
      [
        rows.map((row) => row[0]),
        rows.map((row) => row[1]),
        rows.map((row) => row[2]),
        rows.map((row) => row[3]),
        rows.map((row) => row[4]),
        rows.map((row) => row[5]),
        rows.map((row) => row[6]),
        rows.map((row) => row[7]),
        rows.map((row) => row[8]),
        rows.map((row) => row[11]),
        rows.map((row) => row[12]),
        rows.map((row) => row[13]),
        rows.map((row) => row[14]),
      ],
    );
  }

  /**
   * Resolves `parentSlug` and `bottlerSlug` to ids once every row exists,
   * exactly as the seed importer does. A reference to a slug that exists
   * nowhere is dropped rather than raising — the merge report already named
   * it, and a dangling parent costs a sibling arbitration, not a wrong fact.
   *
   * @param queryRunner - The running migration's query runner.
   * @param rows - The parsed producers.
   */
  private async linkReferences(
    queryRunner: QueryRunner,
    rows: string[][],
  ): Promise<void> {
    const linked = rows.filter((row) => row[9] || row[10]);

    if (!linked.length) {
      return;
    }

    await queryRunner.query(
      `UPDATE producer p SET
         "parentId" = parent.id,
         "bottlerId" = bottler.id
       FROM unnest($1::text[], $2::text[], $3::text[])
         AS v(slug, "parentSlug", "bottlerSlug")
       LEFT JOIN producer parent ON parent.slug = nullif(v."parentSlug", '')
       LEFT JOIN producer bottler ON bottler.slug = nullif(v."bottlerSlug", '')
       WHERE p.slug = v.slug`,
      [
        linked.map((row) => row[0]),
        linked.map((row) => row[9]),
        linked.map((row) => row[10]),
      ],
    );
  }

  /**
   * Inserts the new spellings, already normalized by the merge. An existing
   * key is left with its existing owner — retargeting is a human decision.
   *
   * @param queryRunner - The running migration's query runner.
   * @param rows - The parsed aliases.
   */
  private async insertAliases(
    queryRunner: QueryRunner,
    rows: string[][],
  ): Promise<void> {
    await queryRunner.query(
      `INSERT INTO producer_alias (key, "producerId", scope)
       SELECT v.key, p.id, v.scope
       FROM unnest($1::text[], $2::text[], $3::text[])
         AS v(key, slug, scope)
       JOIN producer p ON p.slug = v.slug
       ON CONFLICT (key) DO NOTHING`,
      [
        rows.map((row) => row[0]),
        rows.map((row) => row[1]),
        rows.map((row) => row[2]),
      ],
    );
  }

  /**
   * Inserts the house-style additions. The composite primary key makes the
   * insert idempotent; an existing statement is never rewritten.
   *
   * @param queryRunner - The running migration's query runner.
   * @param rows - The parsed house styles.
   */
  private async insertFlavors(
    queryRunner: QueryRunner,
    rows: string[][],
  ): Promise<void> {
    await queryRunner.query(
      `INSERT INTO producer_flavor
         ("producerId", "flavorId", effect, confidence, "sourceUrls", note)
       SELECT p.id, f.id, v.effect,
              nullif(v.confidence, ''), nullif(v."sourceUrls", ''),
              nullif(v.note, '')
       FROM unnest(
         $1::text[], $2::text[], $3::text[], $4::text[], $5::text[],
         $6::text[]
       ) AS v(slug, flavor, effect, confidence, "sourceUrls", note)
       JOIN producer p ON p.slug = v.slug
       JOIN flavor f ON f.name = v.flavor
       ON CONFLICT ("producerId", "flavorId") DO NOTHING`,
      [
        rows.map((row) => row[0]),
        rows.map((row) => row[1]),
        rows.map((row) => row[2]),
        rows.map((row) => row[3]),
        rows.map((row) => row[4]),
        rows.map((row) => row[5]),
      ],
    );
  }

  /**
   * Inserts the name-pattern rules, patterns already normalized by the merge.
   *
   * @param queryRunner - The running migration's query runner.
   * @param rows - The parsed rules.
   */
  private async insertRules(
    queryRunner: QueryRunner,
    rows: string[][],
  ): Promise<void> {
    await queryRunner.query(
      `INSERT INTO flavor_rule
         ("producerId", pattern, "matchMode", "flavorId", effect,
          "peatProfile", priority, "sourceUrls", note)
       SELECT p.id, v.pattern, v."matchMode", f.id,
              nullif(v.effect, ''), nullif(v."peatProfile", ''),
              v.priority::int, nullif(v."sourceUrls", ''), nullif(v.note, '')
       FROM unnest(
         $1::text[], $2::text[], $3::text[], $4::text[], $5::text[],
         $6::text[], $7::text[], $8::text[], $9::text[]
       ) AS v(slug, pattern, "matchMode", flavor, effect, "peatProfile",
              priority, "sourceUrls", note)
       JOIN producer p ON p.slug = v.slug
       LEFT JOIN flavor f ON f.name = nullif(v.flavor, '')
       ON CONFLICT ("producerId", pattern, "flavorId") DO NOTHING`,
      [
        rows.map((row) => row[0]),
        rows.map((row) => row[1]),
        rows.map((row) => row[2]),
        rows.map((row) => row[3]),
        rows.map((row) => row[4]),
        rows.map((row) => row[5]),
        rows.map((row) => row[6]),
        rows.map((row) => row[7]),
        rows.map((row) => row[8]),
      ],
    );
  }
}
