export enum Resource {
  AUTHENTICATED = 'authenticated',
  DASHBOARD = 'dashboard',
  MESSAGE = 'message',
  PERMISSION = 'permission',
  PREFERENCE = 'preference',
  PRODUCER = 'producer',
  PRODUCT = 'product',
  PUBLIC = 'public',
  QUICK_FILTER = 'quick_filter',
  SELF = 'self',
  SESSION = 'session',
  STORE = 'store',
  USER = 'user',
}
